#!/bin/bash

CONF="/home/$USER/scripts/data/ubuntu_user.sh"

source $CONF

function x2x_menu() {
    pos=$(echo -e "East\nNorth\nWest\nSouth\nExit" | dmenu -l 5 | tr "[:upper:]" "[:lower:]")
    echo "pos = $pos"
    if [[ $pos != "Exit" ]]; then
        # ref=$(echo -e "0\n1\n2\nExit" | dmenu -l 4)
        ref=0
        echo "ref = $ref"
        if [[ $ref != "Exit" ]]; then
            # com="$user@$ip'x2x -$(echo $pos | tr '[:upper:]' '[:lower:]' ) -to :$(echo $ref).0'"

            echo $com
            # ssh -YC $(echo "$com")
            ssh -YC $user@$ip x2x -east -to :0.0
            # ssh -YC $user@$ip"'x2x -west -to :0'"
        fi
    fi
}

function ssh_menu() {
    echo "ssh connection"
    ssh $user@$ip
}

function mnt_menu() {
    mnt_select=$(echo -e "mount\numount\nexit" | dmenu -l 3)
    if [[ $mnt_select == "mount" ]]; then
        mkdir -p $mnt
        sshfs -o allow_other,default_permissions $user@$password:$/target_home $mnt
    elif [[ $mnt_select == "umount" ]]; then
        umount $mnt
        rmdir $mnt
    fi
}



function main() {
    main_menu="ssh\nx2x\nmnt\nexit"
    select=$(echo -e $main_menu | dmenu -l 4)
    if [[ $select == 'ssh' ]]; then
        ssh_menu
    elif [[ $select == 'x2x' ]]; then
        x2x_menu
    elif [[ $select == 'mnt' ]]; then
        mnt_menu
    fi
}


main
