#!/bin/bash

CURRENT=$(netctl list | grep -e '*' | awk '{print $2}')
SWAPA="TP-LINK_FRA_5"
SWAPB="wlp1s0-Tele2Internet-59ABE"
function swaping() {
    echo "Stop $1: start $2"
    netctl stop $1
    sleep 1
    netctl start $2
}

if [[ $CURRENT =~ "" ]]; then
    echo "Connection $CURRENT"
    if [[ $CURRENT -eq $SWAPA ]]; then
        swaping $SWAPA $SWAPB
        OUT=$?
    else
        swaping $SWAPB $SWAPA
        OUT=$?
    fi
    if [[ $OUT -eq 1 ]]; then
        echo "Swapping done"
        COUNTER=100
        PINGWORKED=1
        while [[ ! PINGWORKED -eq 0 ]]; do
            ping -c 1 8.8.8.8 > /dev/null
            PINGWORKED=$?
            COUNTER=$((COUNTER - 1))
            sleep 1
            if [[ COUNTER -eq 0 ]]; then
                echo "Failed tho create a connection! exit"
                exit -1
            fi
        done
    fi


fi
start-testnet
